App/urls.py
from django.contrib import admin
from django.urls import path
from .import views as v

urlpatterns = [
    path('admin/', admin.site.urls),

    # Admin Urls
    path('',v.Index_Page),
    # Admin Dashboard Url
    path('dashboard',v.AdminDashboard),
   
    path('logout_user',v.Logout_user),
    # Admin Uploaded file Data View url
    path('view_file/<int:id>',v.Admin_file_view),
    # Delete File
    path('delete_file/<int:id>',v.Delete),
    # Push File To Qc
    path('push/<int:id>',v.Push_to_Qc),
    # Send Files History Url
    path('qc_file_record',v.Qc_history),
    # Editor received Url
    path('ed_file_record',v.Ed_record),
    # All user List
    path('all_user',v.All_user),
    # Download File
    path('Download/<int:id>',v.Download),
    # About-us url
    path('about_us',v.About),
    # Feature Page
    path('feature',v.Feature),

    # # delete user
    # path('d_user/<int:id>',v.Delete_user),


    # Qc User Profile Create Url
    path('make_qc',v.Make_Qc),
    # Qc User Login Url
    path('qc_login',v.QC_login), 
    # Otp Verification Url
    path('verify_otp',v.verify_otp),
    # QC Dashboard Url
    path('qc_home',v.QC_home),
    # QC Profile Show Url
    path('qc_view_file/<int:id>',v.QC_file_view),
    # Delete File
    path('del_qc/<int:id>',v.Delete_qc),
    # QC Apply Filter
    path('filter_srh/<int:id>',v.Qc_filter),
    # Qc Edit file Data
    path('qc_edit_data/<int:id>/<int:pid>',v.Qc_edit_date),
    # Qc AFter Filetr edit data
    path('qc_edit_filter_data/<int:id>/<int:pid>',v.Qc_filter_edit),
    # Qc Bulk-Edit Url
    path('data_srh/<int:id>',v.Bulk_Data_save),
    # Add Rows\Copy Data Full row Url
    path('Add_rows/<int:id>/<int:pid>',v.Add_rows),
    # Filter After Add rows Url
    path('filter_Add_rows/<int:id>/<int:pid>',v.filter_Add_rows),
    # Qc Delete Rows
    path('qc_delete_data/<int:id>/<int:pid>/',v.Delete_row),
    # File Send To Final Editor
    path('qc_push/<int:id>',v.Send_file),
    

     # Editor User Profile Create Url
    path('make_ed',v.Make_ed),
    # Editor Login url
    path('ed_login',v.ED_login),
    # Otp Verification Url
    path('verify_otp1',v.verify_otp1),
     # Editor Dashboard Url
    path('ed_home',v.ED_home),
    
    path('ed_view_file/<int:id>',v.Ed_file_view),
    # Editor Apply Filter
    path('ed_filter_srh/<int:id>',v.Ed_filter),
    # Editor Bulk-Edit Url
    path('ed_data_srh/<int:id>',v.Ed_Bulk_Data_save),
    # Editor Edit file Data
    path('ed_edit_data/<int:id>/<int:pid>',v.Ed_edit_date),
    # Editor AFter Filetr edit data
    path('ed_edit_filter_data/<int:id>/<int:pid>',v.Ed_filter_edit),
    # Final File Send To Admin For Download
    path('ed_push/<int:id>',v.Ed_Send_file),
    # Error/Doubts Url
    # path('message/<int:id>',v.Message),
]

Web/urls.py
from django.contrib import admin
from django.urls import path,include
from Web import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms

# Create your models here.
    
class My_Upload_file(models.Model):
    file=models.FileField()
    count=models.IntegerField(null=True)
    o_len=models.IntegerField(null=True)
    from_date=models.CharField(max_length=100,null=True)
    to_date=models.CharField(max_length=100,null=True)
    status=models.BooleanField(default=False)
    date=models.DateField(auto_now=True)
    def __str__(self):
        return self.file.name

    
class Qc_user(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)   
    def __str__(self):
        u=self.user.first_name+'-'+self.user.last_name
        return u
    
class my_Qc_data(models.Model):
    my_file=models.ForeignKey(My_Upload_file,on_delete=models.CASCADE)
    qc_file=models.FileField(upload_to='qc')
    from_date=models.CharField(max_length=100,null=True)
    to_date=models.CharField(max_length=100,null=True)
    user=models.ForeignKey(Qc_user,on_delete=models.CASCADE)
    start=models.IntegerField(default=0)
    date=models.DateField(auto_now=True)
    end=models.IntegerField()
    status=models.BooleanField(default=False)
    
    

class qc_Form(forms.ModelForm):
    class Meta:
        model=my_Qc_data
        fields=['user']



class ED_User(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)  
    def __str__(self):
        u=self.user.first_name+'-'+self.user.last_name
        return u

class Editor_push(models.Model):
    Editior=models.ForeignKey(ED_User,on_delete=models.CASCADE)
    qc_data=models.ForeignKey(my_Qc_data,on_delete=models.CASCADE)
    qc_user=models.ForeignKey(Qc_user,on_delete=models.CASCADE)
    rec_length=models.IntegerField()
    date=models.DateField(auto_now=True)
    sta=models.BooleanField(default=False)
    def __str__(self):
        return self.qc_data.qc_file.name
    

class pushForm(forms.ModelForm):
    class Meta:
        model=Editor_push
        fields=['Editior']


class Final_data_PM(models.Model):

    Editior=models.ForeignKey(ED_User,on_delete=models.CASCADE)
    Edited_file=models.ForeignKey(Editor_push,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)    
    status=models.BooleanField(default=False)

class Doubt(models.Model):
    file=models.ForeignKey(my_Qc_data,on_delete=models.CASCADE)
    user=models.ForeignKey(Qc_user,on_delete=models.CASCADE)
    Sr_no=models.CharField(max_length=100)
    msg=models.CharField(max_length=2000)

App/templates/admin_temps/All_user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Report</title>
    {%load static%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 14px;
            font-family: Arial, sans-serif;
        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
            color: #333;
        }

        tr:hover {
            background-color: #ccc;
        }

        .a_back {
            text-decoration: none;
            color: #c9cc00;
            font-size: 18px;
            background-color: rgb(125, 114, 114);
            padding-left: 4px;
            padding-right: 4px;
            padding-top: 2px;
            padding-bottom: 2px;
            float: right;
            margin-right: 5px;
        }

        .a_back:hover {
            color: #0099cc;
            background-color: #ccc;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">

            <a class="navbar-brand" href="#">
                <img src="/static/image/logo.png" alt="Logo" width="270" height="50">

            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    
                    <li class="nav-item">
                        <a class="nav-link active mt-2" aria-current="page" href="/dashboard">Home</a>
                    </li>
                    <li class="nav-item" style="margin-left: 600px;">
                        <p class="text-light fs-6 nav-link active mt-2 "><strong class="text-light">User - </strong> <b>{{user}}</b></p>

                    </li>
                    
                </ul>
            </div>
        </div>
    </nav>
    <h1 class="text-center text-secondary">Here Your User's</h1>

    {% for user_type, users in user_types.items %}
    <h2 style="font-size: 20px;text-align:left;font-weight: 700;" class="text-danger">{{ user_type }} User's</h2>
    <table>
        <tr>
            <th class="text-secondary text-center">First Name</th>
            <th class="text-secondary text-center">Last Name</th>
            <th class="text-secondary text-center">Email</th>
            <th class="text-secondary text-center">Username</th>
            <!-- <th class="text-danger text-center">Delete User</th> -->

        </tr>
        {% for user in users %}
        <tr>
            <td style="font-weight: 600;" class="text-primary text-center">{{ user.user.first_name }}</td>
            <td style="font-weight: 600;" class="text-primary text-center">{{ user.user.last_name }}</td>
            <td style="font-weight: 600;" class="text-primary text-center">{{ user.user.email }}</td>
            <td style="font-weight: 600;" class="text-primary text-center">{{ user.user.username }}</td>
            <!-- <td><a href="d_user/{{user.id}}">Delete</a></td> -->
        </tr>
        {% endfor %}
    </table>
    {% endfor %}
</body>

</html>

App/templates/admin_temps/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About-us</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <style>
            body{
                font-family: Verdana, Geneva, Tahoma, sans-serif;
            }
        </style>
</head>

<body>

    <div class="container">
        <!-- About 3 - Bootstrap Brain Component -->
        <section class="py-3">
            <div class="container ">
                <div class="row justify-content-md-center">
                    <div class="col-12 col-md-10 col-xxl-8">
                        <img class="img-fluid" loading="lazy" src="/static/image/logo.png" height="60px" width="300px"
                            alt="About 3">
                    </div>
                </div>
            </div>

            <div class="container overflow-hidden">
                <div class="row gy-2 gy-md-0 justify-content-xxl-center">
                    <div class="col-12 order-md-1 col-md-8 col-xxl-6">
                        <div class="text-center text-md-start">
                            <h2 class="display-3 fw-bold lh-1">Kasturirangan P</h2>
                            <p class="text-secondary">Founder & CEO of <b><i>Krima Solutions</i></b></p>
                            <hr class="w-25 mx-auto ms-md-0  text-secondary">
                            <h3 class="text-center" style="color: rgb(104, 102, 102);font-size: 28px;font-weight: 300;">
                                We Are Krima Solutions
                            </h3>
                            <h4 class="text-center" style="color: black;font-weight: 700;font-size: 28px;">We deliver
                                thought out solutions....through technology.</h4>
                            <p style="overflow-y: scroll;height: 270px;">Krima Solutions is a new economy firm that
                                believes in <mark
                                    style="color: rgb(233, 134, 6);background-color: transparent;">technology enabled
                                    services</mark> that
                                enhance end-customer experience of digital assets owned by corporations, digital
                                publishing firms, event firms and ecommerce companies. Krima provides entire <mark
                                    style="color: rgb(233, 134, 6);background-color: transparent;">digital
                                    lifecycle services</mark> for building and maintaining digital assets. We plan for,
                                design and
                                conceptualise digital assets. Developing <mark
                                    style="color: rgb(233, 134, 6);background-color: transparent;">customer-focused
                                    UX/UI</mark> and providing
                                <mark style="color: rgb(233, 134, 6);background-color: transparent;">researched
                                    content</mark> and its ongoing maintenance is our core expertise. We provide
                                on-going and
                                routine <mark style="color: rgb(233, 134, 6);background-color: transparent;">forensics
                                    on online user behaviour</mark> & preferences and help clients tweak their
                                digital design and content strategy for more effective results.

                                We have been able to solve several challenges and pain-staking problems to generate
                                meaningful and relevant data from unstructured, disparate medium of information onto a
                                structured database/platform. Our clients can get access to <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;">processed information
                                    on a
                                    near-live basis </marl> with speed and accuracy. <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;">AI created machine
                                    learning algorithms</marl>
                                constantly improve themselves.

                                SMART BASICS is what we follow. No big frills of huge physical infrastructure, but one
                                that is functional and top class in effectiveness. A huge focus on working with
                                best-in-class professionals we believe in <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;font-size: 16px;">
                                    "SMART BASICS"</marl>. Clients fully leverage their
                                access to our skilled resources be it automation experts or researchers and analysts.
                                Our deliverables focus purely on three simple things: correctness, completeness and
                                timeliness. This enables our objective of enabling our clients to enhance value through
                                cost and beyond.

                                Innovation, problem solving ability, proactivity from Krima Solutions will help you
                                enhance your brands and the digital assets. We help you with <marl
                                    style="color: rgb(233, 134, 6);background-color: transparent;">technology that is
                                    cutting-edge;</marl> one that is effective, efficient, result oriented and yes,
                                definitely
                                disruptive.
                            </p>

                        </div>
                    </div>
                    <div class="col-12 order-md-0 col-md-4 col-xxl-4">
                        <div class="text-center text-md-start me-md-3 me-xl-5">
                            <p class="mb-4">
                                <span class="d-block display-6 lh-1">Startup</span>
                                <span class="fs-4 text-secondary">Growing Startup</span>
                            </p>
                            <div class="d-grid">

                                <a href="/" class="btn btn-outline-primary btn-lg">Home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>




</body>

</html>

App/templates/admin_temps/ed_record.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KrimaSolutions-Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body {
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 14px;
            
        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
            color: #333;
        }

        tr:hover {
            background-color: #ccc;
        }

        .a_back {
            text-decoration: none;
            color: #c9cc00;
            font-size: 18px;
            background-color: rgb(125, 114, 114);
            padding-left: 4px;
            padding-right: 4px;
            padding-top: 2px;
            padding-bottom: 2px;
            float: right;
            margin-right: 5px;
        }

        .a_back:hover {
            color: #0099cc;
            background-color: #ccc;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="/static/image/logo.png" alt="Logo" width="270" height="50">

            </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    {% load utils %}

                    {% with request.path|split_path as path_parts %}
                    {% with path_parts|last as file_id %}
                    {% if request.path|startswith:'/work_repo/' and file_id|isdigit %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/qc_file_record"
                            style="font-size: 19px;">Report</a>
                    </li>
                    {%else%}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/dashboard"
                            style="font-size: 19px;">Home</a>
                    </li>
                    <li class="nav-item" style="margin-left: 500px;">
                        <p class="text-light fs-6 nav-link active "><strong class="text-light">User - </strong> <b>{{user}}</b></p>

                    </li>
                    {% endif %}

                    {% endwith %}
                    {% endwith %}
                    
                </ul>
            </div>
        </div>
    </nav>
    <h2 style="color: #00698f; font-size: 20px;text-align: center;text-decoration: underline;">Records Report</h2>
{%if data%}
    <div class="container">
        {% regroup data by Edited_file.qc_data.my_file as files %}
        {% for file in files %}
        
        <h3 style="color: #0099cc; font-size: 18px;font-weight: 600;">{{ file.grouper }} ({{ file.list|length }} records)</h3>
        <table>
            <tr>
                <th class="bg-success text-light">Editior User</th>
                <th class="bg-info">Receive File Date</th>
                <th class="bg-success text-light">File Name</th>
                <!-- <th>Original File</th> -->
                <th class="bg-secondary text-light">Before Edit</th>
                <th class="bg-success text-light"> After Edit</th>
                <!-- <th>Recive Date</th> -->
                <th class="bg-secondary text-light">Record's Date</th>
                <th class="bg-success text-light">Download File</th>
            </tr>
            {% for i in file.list %}
            <tr>
                <td class="text-center text-light bg-success">{{i.Editior}}</td>
                <td class="text-center bg-info text-dark">{{i.date}}</td>
                <td class="text-primary text-light bg-success ">
                    <abbr title="{{i.Edited_file.qc_data.qc_file}}" style="text-decoration: none;" > {{i.Edited_file.qc_data.qc_file|truncatechars:30 }}</abbr>
                    </td>
                <!-- <td class="text-primary">
                    <abbr title="{{i.Edited_file.qc_data.my_file}}" style="text-decoration: none;" > {{i.Edited_file.qc_data.my_file|truncatechars:20 }}</abbr>
                    </td> -->
                <td class="text-center bg-secondary text-light ">{{i.Edited_file.qc_data.end}}</td>
                <td class="text-center bg-success text-light">{{i.Edited_file.rec_length}}</td>
                <!-- <td>{{i.date}}</td> -->
                <td class="text-center bg-secondary text-light">{{i.Edited_file.qc_data.from_date}} - {{i.Edited_file.qc_data.to_date}}</td>
                <td class="text-center"><a href="Download/{{i.id}}"
                        style="text-decoration: none;font-size: 15px;font-weight: 700;">Download</a></td>
            </tr>
            {% endfor %}
        </table>
        {% endfor %}
    </div>
    {%else%}
    <div class="container text-center" style="margin-top: 40px;margin-bottom: 50px;">

        <div class="spinner-border m-5" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <h3>Not Any Files Received Here</h3>
        

    </div>
    {%endif%}
   
</body>

</html>

App/templates/admin_temps/push_form.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Record Assgin Form</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body {
            background-color: #f5f5f5;
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }

        .container {
            max-width: 1100px;
            margin: 20px auto;
            padding: 20px;
            background-color: #fff;
            border: 1px solid #ddd;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            border-radius: 20px;
        }

        .form-label {
            font-weight: bold;
        }

        .form-control {
            height: 40px;
            padding: 10px;
            font-size: 16px;
            border-radius: 10px;
        }

        .btn-primary {
            width: 100%;
            font-size: 18px;
            padding: 10px;
            border-radius: 20px;
        }
        .btn-outline-success {
            width: 100%;
            font-size: 18px;
            padding: 10px;
        }
    </style>
</head>

<body>
    <div>
        <h4><a href="/dashboard" class="btn btn-outline-success">Back To Home</a></h4>
    </div>
    <div class="d-flex align-items-center">
        <img src="/static/image/logo.png" alt="" style="width: 310px; height: 50px; ">
        
            <p class="text-dark fs-5 nav-link active " style="margin-left: 640px;"><strong class="text-dark">User - </strong> <b>{{user}}</b></p>

       
        
    </div>
    <h2 class="text-center p-2">Record Assign Form</h2>
    <div class="container d-flex" style="width: 100%;">
        <div class="container shadow-lg bg-white rounded" style="width: 100%;">
            <form class="row g-3" method="post">
                {% csrf_token %}
                <div class="col-12 form-label">
    
                    {{ form.as_table }}
                </div>
                <div class="col-12">
                    <label for="id_user" class="form-label">Enter Name For Creating File:</label>
                    <input type="text" name="file_name" id="" placeholder="qc_12" required class="form-control">
                </div>
                <div class="col-12">
                    <label for="id_user" class="form-label">Number Of Records:</label>
                    <input type="number" name="end" id="" required placeholder="End Record Number" class="form-control">
                </div>
                <div class="col-12 text-center">
                    <button type="submit" class="btn btn-primary">Assign</button>
                </div>
            </form>
        </div>
        <div class="container">
            <table class="table table-hover">
                <h3 class="text-center my-4 mx-2 py-2 px-2">File Stats</h3>
                <tr>
                    <th class="text-dark  text-center">File Name</th>
                    <th class="text-dark  text-center">Records Length</th>
                    <th class="text-dark  text-center">Upload Date</th>
                </tr>
                <tr>
                    <td class="text-center">
                        <abbr title=" {{name}}" style="text-decoration: none;" >{{name|truncatechars:20}}</abbr></td>
                    <td class="text-center">{{length}}</td>
                    <td class="text-center">{{date}}</td>
                </tr>
            </table>

        </div>

    </div>
</body>

</html>

App/templates/admin_temps/qc_record.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>KrimaSolutions-Report</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
        body {
            font-family: Verdana, Geneva, Tahoma, sans-serif;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 14px;

        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
            color: #333;
        }

        tr:hover {
            background-color: #ccc;
        }

        .a_back {
            text-decoration: none;
            color: #c9cc00;
            font-size: 18px;
            background-color: rgb(125, 114, 114);
            padding-left: 4px;
            padding-right: 4px;
            padding-top: 2px;
            padding-bottom: 2px;
            float: right;
            margin-right: 5px;
        }

        .a_back:hover {
            color: #0099cc;
            background-color: #ccc;
        }

        .table-fixed {
            table-layout: fixed;
        }

        .table-fixed th,
        .table-fixed td {
            width: 150px;
            /* adjust the width to fit your needs */
            height: 40px;
            /* adjust the height to fit your needs */
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }

        .table-fixed th {
            background-color: #f0f0f0;
        }

        .table-fixed td {
            border-bottom: 1px solid #ddd;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="#">
                <img src="/static/image/logo.png" alt="Logo" width="270" height="50">

            </a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">


                    {% load utils %}

                    {% with request.path|split_path as path_parts %}
                    {% with path_parts|last as file_id %}
                    {% if request.path|startswith:'/work_repo/' and file_id|isdigit %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/qc_file_record"
                            style="font-size: 19px;">Report</a>
                    </li>
                    {%else%}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/dashboard"
                            style="font-size: 19px;">Home</a>
                    </li>
                    <li class="nav-item" style="margin-left: 500px;">
                        <p class="text-light fs-6 nav-link active "><strong class="text-light">User - </strong> <b>{{user}}</b></p>

                    </li>
                    {% endif %}

                    {% endwith %}
                    {% endwith %}

                </ul>
            </div>
        </div>
    </nav>
    <h2 style="color: #00698f; font-size: 20px;text-align: center;text-decoration: underline;">Records Report</h2>
{%if combined_list%}
    <div class="container">

        {% for key, group in combined_list|group_by:"my_file" %}
        <h3 style="color: #0099cc; font-size: 18px;font-weight: 600;">{{ key }} ({{ group|length }} records)</h3>

        <table class="d-flex table-fixed">
            <tr>
                <th>Qc User</th>
                <th>Send File Date</th>
                <th>File Name</th>
                <th>Records</th>
                <th>From Date</th>
                <th>To Date</th>
                <th colspan="3" class="text-center">Work Status</th>
                
            </tr>
            {% for item in group %}
            <tr>
                <td>{{ item.0.user }}</td>
                <td>{{ item.0.date }}</td>
                <td>{{ item.0.qc_file }}</td>
                <td>{{ item.0.end }}</td>
                <td>{{ item.0.from_date }}</td>
                <td>{{ item.0.to_date }}</td>
                <td class="text-center d-flex" style="width:210px;">
                    <p class="bg-secondary" style="width: 35px;height: 25px;">
                        <b class=" text-light rounded-pill py-2 px-2">{{ item.1.unclassified }}</b>
                    </p>
                    <p class="bg-success" style="width: 35px;height: 25px;">

                        <b class="text-light  rounded-pill  py-2 px-2">{{ item.1.correct }}</b>
                    </p>
                    <p class="bg-warning" style="width: 35px;height: 25px;">

                        <b class=" text-light rounded-pill  py-2 px-2">{{ item.1.error }}</b>
                    </p>
                    <p class="bg-danger" style="width: 35px;height: 25px;">

                        <b class=" text-light rounded-pill  py-2 px-2">{{ item.1.rejected }}</b>
                    </p>
                    <p class="bg-dark" style="width: 45px;height: 25px;">

                        <b class=" text-light rounded-pill  py-2 px-2">B-{{ item.1.rejected }}</b>
                    </p>
                </td>
                
            </tr>
            {% endfor %}
        </table>
        {% endfor %}
    </div>
    {%else%}
    <div class="container text-center" style="margin-top: 40px;margin-bottom: 50px;">

        <div class="spinner-border m-5" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
        <h3>No Files Uploaded as Yet</h3>
        <p>Upload Files To Start Work</p>

    </div>
    
    {%endif%}

</body>

</html>